// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateMetricsParams struct {
	Time            pgtype.Timestamptz
	DeviceName      pgtype.Text
	DeviceID        pgtype.Int4
	RegisterName    pgtype.Text
	RegisterAddress pgtype.Int4
	Value           pgtype.Int4
}
