// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMetric = `-- name: CreateMetric :exec
INSERT INTO metrics (
  time, device_id, register_name, register_address, "value"
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateMetricParams struct {
	Time            pgtype.Timestamptz
	DeviceID        pgtype.Int4
	RegisterName    pgtype.Text
	RegisterAddress pgtype.Int4
	Value           pgtype.Int4
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) error {
	_, err := q.db.Exec(ctx, createMetric,
		arg.Time,
		arg.DeviceID,
		arg.RegisterName,
		arg.RegisterAddress,
		arg.Value,
	)
	return err
}
